plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-image-size
  - jekyll-fetch
  - jemoji

permalink: /:slugified_categories/:year/:month/:title:output_ext
excerpt_separator: "#"

url: https://pierre-couy.dev
title: Pierre Couy's tech corner
author: Pierre Couy
description: Freelance developper, computer science teacher, passionate about programming. I enjoy sharing my work with the world.

jekyll-archives:
  enabled: all

kramdown:
  parse_block_html: true
  toc_levels: 2..6

collections:
  projects:
    sort_by: order
    output: true
    layout: post.html
