plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:slugified_categories/:year/:month/:title:output_ext
  
title: Pierre Couy's tech corner
author: Pierre Couy
description: Freelance developper, computer science teacher, passionate about programming. I enjoy sharing my work with the world.

jekyll-archives:
  enabled: all

